# This file is @generated by tarina.lang CLI tool
# It is not intended for manual editing.

from tarina.lang.model import LangItem, LangModel  # type: ignore[import-untyped]


class InteractionWrong:
    query_bot: LangItem = LangItem('interaction', 'wrong.query_bot')


class InteractionWarning:
    unverified: LangItem = LangItem('interaction', 'warning.unverified')


class Interaction:
    wrong = InteractionWrong
    warning = InteractionWarning


class ErrorMessageformaterror:
    TETR_IO: LangItem = LangItem('error', 'MessageFormatError.TETR.IO')
    TOS: LangItem = LangItem('error', 'MessageFormatError.TOS')
    TOP: LangItem = LangItem('error', 'MessageFormatError.TOP')


class Error:
    MessageFormatError = ErrorMessageformaterror


class Lang(LangModel):
    interaction = Interaction
    error = Error
