# This file is @generated by tarina.lang CLI tool
# It is not intended for manual editing.

from tarina.lang.model import LangItem, LangModel


class InteractionWrong:
    query_bot: LangItem = LangItem('interaction', 'wrong.query_bot')


class InteractionWarning:
    unverified: LangItem = LangItem('interaction', 'warning.unverified')


class Interaction:
    wrong = InteractionWrong
    warning = InteractionWarning


class ErrorMessageformaterror:
    TETR_IO: LangItem = LangItem('error', 'MessageFormatError.TETR.IO')
    TOS: LangItem = LangItem('error', 'MessageFormatError.TOS')
    TOP: LangItem = LangItem('error', 'MessageFormatError.TOP')
    duration: LangItem = LangItem('error', 'MessageFormatError.duration')


class ErrorRequesterrorRequest:
    api: LangItem = LangItem('error', 'RequestError.request.api')
    cloudflare: LangItem = LangItem('error', 'RequestError.request.cloudflare')
    response: LangItem = LangItem('error', 'RequestError.request.response')
    transport: LangItem = LangItem('error', 'RequestError.request.transport')
    failover: LangItem = LangItem('error', 'RequestError.request.failover')


class ErrorRequesterrorTetrIo:
    leaderboard: LangItem = LangItem('error', 'RequestError.TETR.IO.leaderboard')
    user_info: LangItem = LangItem('error', 'RequestError.TETR.IO.user_info')
    summaries: LangItem = LangItem('error', 'RequestError.TETR.IO.summaries')
    league_history: LangItem = LangItem('error', 'RequestError.TETR.IO.league_history')
    records: LangItem = LangItem('error', 'RequestError.TETR.IO.records')


class ErrorRequesterrorTos:
    user_info: LangItem = LangItem('error', 'RequestError.TOS.user_info')


class ErrorRequesterror:
    request = ErrorRequesterrorRequest
    TETR_IO = ErrorRequesterrorTetrIo
    TOS = ErrorRequesterrorTos


class Error:
    MessageFormatError = ErrorMessageformaterror
    RequestError = ErrorRequesterror


class Template:
    template_language: LangItem = LangItem('template', 'template_language')


class Bind:
    not_found: LangItem = LangItem('bind', 'not_found')
    no_account: LangItem = LangItem('bind', 'no_account')
    confirm_unbind: LangItem = LangItem('bind', 'confirm_unbind')
    confirm_yes: LangItem = LangItem('bind', 'confirm_yes')
    confirm_no: LangItem = LangItem('bind', 'confirm_no')
    config_success: LangItem = LangItem('bind', 'config_success')
    verify_already: LangItem = LangItem('bind', 'verify_already')
    verify_failed: LangItem = LangItem('bind', 'verify_failed')
    only_discord: LangItem = LangItem('bind', 'only_discord')


class Record:
    not_found: LangItem = LangItem('record', 'not_found')
    blitz: LangItem = LangItem('record', 'blitz')
    sprint: LangItem = LangItem('record', 'sprint')


class Stats:
    user_info: LangItem = LangItem('stats', 'user_info')
    no_rank: LangItem = LangItem('stats', 'no_rank')
    rank_info: LangItem = LangItem('stats', 'rank_info')
    no_game: LangItem = LangItem('stats', 'no_game')
    recent_games: LangItem = LangItem('stats', 'recent_games')
    daily_stats: LangItem = LangItem('stats', 'daily_stats')
    no_daily: LangItem = LangItem('stats', 'no_daily')
    history_stats: LangItem = LangItem('stats', 'history_stats')
    no_history: LangItem = LangItem('stats', 'no_history')
    lpm: LangItem = LangItem('stats', 'lpm')
    apm: LangItem = LangItem('stats', 'apm')
    adpm: LangItem = LangItem('stats', 'adpm')
    sprint_pb: LangItem = LangItem('stats', 'sprint_pb')
    marathon_pb: LangItem = LangItem('stats', 'marathon_pb')
    challenge_pb: LangItem = LangItem('stats', 'challenge_pb')


class TemplateUi:
    invalid_tag: LangItem = LangItem('template_ui', 'invalid_tag')
    update_success: LangItem = LangItem('template_ui', 'update_success')
    update_failed: LangItem = LangItem('template_ui', 'update_failed')


class Help:
    usage: LangItem = LangItem('help', 'usage')


class Prompt:
    io_check: LangItem = LangItem('prompt', 'io_check')
    io_bind: LangItem = LangItem('prompt', 'io_bind')
    top_check: LangItem = LangItem('prompt', 'top_check')
    top_bind: LangItem = LangItem('prompt', 'top_bind')
    tos_check: LangItem = LangItem('prompt', 'tos_check')
    tos_bind: LangItem = LangItem('prompt', 'tos_bind')


class Retry:
    message: LangItem = LangItem('retry', 'message')
    screenshot: LangItem = LangItem('retry', 'screenshot')


class CommandRoot:
    description: LangItem = LangItem('command', 'root.description')
    plugin_description: LangItem = LangItem('command', 'root.plugin_description')
    plugin_usage: LangItem = LangItem('command', 'root.plugin_usage')


class CommandTetrioBindArgsAccount:
    notice: LangItem = LangItem('command', 'tetrio.bind.args.account.notice')


class CommandTetrioBindArgs:
    account = CommandTetrioBindArgsAccount


class CommandTetrioBind:
    description: LangItem = LangItem('command', 'tetrio.bind.description')
    args = CommandTetrioBindArgs
    shortcut: LangItem = LangItem('command', 'tetrio.bind.shortcut')


class CommandTetrioConfigOptionsDefaultTemplateArgsTemplate:
    notice: LangItem = LangItem('command', 'tetrio.config.options.default_template.args.template.notice')


class CommandTetrioConfigOptionsDefaultTemplateArgs:
    template = CommandTetrioConfigOptionsDefaultTemplateArgsTemplate


class CommandTetrioConfigOptionsDefaultTemplate:
    help: LangItem = LangItem('command', 'tetrio.config.options.default_template.help')
    args = CommandTetrioConfigOptionsDefaultTemplateArgs


class CommandTetrioConfigOptionsDefaultCompareArgsCompare:
    notice: LangItem = LangItem('command', 'tetrio.config.options.default_compare.args.compare.notice')


class CommandTetrioConfigOptionsDefaultCompareArgs:
    compare = CommandTetrioConfigOptionsDefaultCompareArgsCompare


class CommandTetrioConfigOptionsDefaultCompare:
    help: LangItem = LangItem('command', 'tetrio.config.options.default_compare.help')
    args = CommandTetrioConfigOptionsDefaultCompareArgs


class CommandTetrioConfigOptions:
    default_template = CommandTetrioConfigOptionsDefaultTemplate
    default_compare = CommandTetrioConfigOptionsDefaultCompare


class CommandTetrioConfig:
    description: LangItem = LangItem('command', 'tetrio.config.description')
    options = CommandTetrioConfigOptions
    shortcut: LangItem = LangItem('command', 'tetrio.config.shortcut')


class CommandTetrioListOptionsMaxTr:
    help: LangItem = LangItem('command', 'tetrio.list.options.max_tr.help')


class CommandTetrioListOptionsMinTr:
    help: LangItem = LangItem('command', 'tetrio.list.options.min_tr.help')


class CommandTetrioListOptionsLimit:
    help: LangItem = LangItem('command', 'tetrio.list.options.limit.help')


class CommandTetrioListOptionsCountry:
    help: LangItem = LangItem('command', 'tetrio.list.options.country.help')


class CommandTetrioListOptionsSortArgsSort:
    notice: LangItem = LangItem('command', 'tetrio.list.options.sort.args.sort.notice')


class CommandTetrioListOptionsSortArgs:
    sort = CommandTetrioListOptionsSortArgsSort


class CommandTetrioListOptionsSort:
    help: LangItem = LangItem('command', 'tetrio.list.options.sort.help')
    args = CommandTetrioListOptionsSortArgs


class CommandTetrioListOptions:
    max_tr = CommandTetrioListOptionsMaxTr
    min_tr = CommandTetrioListOptionsMinTr
    limit = CommandTetrioListOptionsLimit
    country = CommandTetrioListOptionsCountry
    sort = CommandTetrioListOptionsSort


class CommandTetrioList:
    description: LangItem = LangItem('command', 'tetrio.list.description')
    options = CommandTetrioListOptions


class CommandTetrioQueryArgsWho:
    notice: LangItem = LangItem('command', 'tetrio.query.args.who.notice')


class CommandTetrioQueryArgs:
    who = CommandTetrioQueryArgsWho


class CommandTetrioQueryOptionsTemplateArgsTemplate:
    notice: LangItem = LangItem('command', 'tetrio.query.options.template.args.template.notice')


class CommandTetrioQueryOptionsTemplateArgs:
    template = CommandTetrioQueryOptionsTemplateArgsTemplate


class CommandTetrioQueryOptionsTemplate:
    help: LangItem = LangItem('command', 'tetrio.query.options.template.help')
    args = CommandTetrioQueryOptionsTemplateArgs


class CommandTetrioQueryOptionsCompareArgsCompare:
    notice: LangItem = LangItem('command', 'tetrio.query.options.compare.args.compare.notice')


class CommandTetrioQueryOptionsCompareArgs:
    compare = CommandTetrioQueryOptionsCompareArgsCompare


class CommandTetrioQueryOptionsCompare:
    help: LangItem = LangItem('command', 'tetrio.query.options.compare.help')
    args = CommandTetrioQueryOptionsCompareArgs


class CommandTetrioQueryOptions:
    template = CommandTetrioQueryOptionsTemplate
    compare = CommandTetrioQueryOptionsCompare


class CommandTetrioQuery:
    description: LangItem = LangItem('command', 'tetrio.query.description')
    args = CommandTetrioQueryArgs
    options = CommandTetrioQueryOptions
    shortcut: LangItem = LangItem('command', 'tetrio.query.shortcut')


class CommandTetrioRankAllOptionsTemplateArgsTemplate:
    notice: LangItem = LangItem('command', 'tetrio.rank.all.options.template.args.template.notice')


class CommandTetrioRankAllOptionsTemplateArgs:
    template = CommandTetrioRankAllOptionsTemplateArgsTemplate


class CommandTetrioRankAllOptionsTemplate:
    help: LangItem = LangItem('command', 'tetrio.rank.all.options.template.help')
    args = CommandTetrioRankAllOptionsTemplateArgs


class CommandTetrioRankAllOptions:
    template = CommandTetrioRankAllOptionsTemplate


class CommandTetrioRankAll:
    description: LangItem = LangItem('command', 'tetrio.rank.all.description')
    options = CommandTetrioRankAllOptions


class CommandTetrioRankDetailArgsRank:
    notice: LangItem = LangItem('command', 'tetrio.rank.detail.args.rank.notice')


class CommandTetrioRankDetailArgs:
    rank = CommandTetrioRankDetailArgsRank


class CommandTetrioRankDetail:
    description: LangItem = LangItem('command', 'tetrio.rank.detail.description')
    args = CommandTetrioRankDetailArgs


class CommandTetrioRank:
    description: LangItem = LangItem('command', 'tetrio.rank.description')
    all = CommandTetrioRankAll
    detail = CommandTetrioRankDetail
    shortcut: LangItem = LangItem('command', 'tetrio.rank.shortcut')


class CommandTetrioRecordArgsWho:
    notice: LangItem = LangItem('command', 'tetrio.record.args.who.notice')


class CommandTetrioRecordArgs:
    who = CommandTetrioRecordArgsWho


class CommandTetrioRecordOptionsTypeArgsRecordType:
    notice: LangItem = LangItem('command', 'tetrio.record.options.type.args.record_type.notice')


class CommandTetrioRecordOptionsTypeArgs:
    record_type = CommandTetrioRecordOptionsTypeArgsRecordType


class CommandTetrioRecordOptionsType:
    help: LangItem = LangItem('command', 'tetrio.record.options.type.help')
    args = CommandTetrioRecordOptionsTypeArgs


class CommandTetrioRecordOptionsIndexArgsIndex:
    notice: LangItem = LangItem('command', 'tetrio.record.options.index.args.index.notice')


class CommandTetrioRecordOptionsIndexArgs:
    index = CommandTetrioRecordOptionsIndexArgsIndex


class CommandTetrioRecordOptionsIndex:
    help: LangItem = LangItem('command', 'tetrio.record.options.index.help')
    args = CommandTetrioRecordOptionsIndexArgs


class CommandTetrioRecordOptions:
    type = CommandTetrioRecordOptionsType
    index = CommandTetrioRecordOptionsIndex


class CommandTetrioRecordShortcuts:
    blitz: LangItem = LangItem('command', 'tetrio.record.shortcuts.blitz')
    sprint: LangItem = LangItem('command', 'tetrio.record.shortcuts.sprint')


class CommandTetrioRecord:
    args = CommandTetrioRecordArgs
    options = CommandTetrioRecordOptions
    shortcuts = CommandTetrioRecordShortcuts


class CommandTetrioUnbind:
    description: LangItem = LangItem('command', 'tetrio.unbind.description')
    shortcut: LangItem = LangItem('command', 'tetrio.unbind.shortcut')


class CommandTetrioVerify:
    description: LangItem = LangItem('command', 'tetrio.verify.description')
    shortcut: LangItem = LangItem('command', 'tetrio.verify.shortcut')


class CommandTetrio:
    description: LangItem = LangItem('command', 'tetrio.description')
    bind = CommandTetrioBind
    config = CommandTetrioConfig
    list = CommandTetrioList
    query = CommandTetrioQuery
    rank = CommandTetrioRank
    record = CommandTetrioRecord
    unbind = CommandTetrioUnbind
    verify = CommandTetrioVerify


class CommandTopBindArgsAccount:
    notice: LangItem = LangItem('command', 'top.bind.args.account.notice')


class CommandTopBindArgs:
    account = CommandTopBindArgsAccount


class CommandTopBind:
    description: LangItem = LangItem('command', 'top.bind.description')
    args = CommandTopBindArgs
    shortcut: LangItem = LangItem('command', 'top.bind.shortcut')


class CommandTopUnbind:
    description: LangItem = LangItem('command', 'top.unbind.description')
    shortcut: LangItem = LangItem('command', 'top.unbind.shortcut')


class CommandTopConfigOptionsDefaultCompareArgsCompare:
    notice: LangItem = LangItem('command', 'top.config.options.default_compare.args.compare.notice')


class CommandTopConfigOptionsDefaultCompareArgs:
    compare = CommandTopConfigOptionsDefaultCompareArgsCompare


class CommandTopConfigOptionsDefaultCompare:
    help: LangItem = LangItem('command', 'top.config.options.default_compare.help')
    args = CommandTopConfigOptionsDefaultCompareArgs


class CommandTopConfigOptions:
    default_compare = CommandTopConfigOptionsDefaultCompare


class CommandTopConfig:
    description: LangItem = LangItem('command', 'top.config.description')
    options = CommandTopConfigOptions
    shortcut: LangItem = LangItem('command', 'top.config.shortcut')


class CommandTopQueryArgsWho:
    notice: LangItem = LangItem('command', 'top.query.args.who.notice')


class CommandTopQueryArgs:
    who = CommandTopQueryArgsWho


class CommandTopQueryOptionsCompareArgsCompare:
    notice: LangItem = LangItem('command', 'top.query.options.compare.args.compare.notice')


class CommandTopQueryOptionsCompareArgs:
    compare = CommandTopQueryOptionsCompareArgsCompare


class CommandTopQueryOptionsCompare:
    help: LangItem = LangItem('command', 'top.query.options.compare.help')
    args = CommandTopQueryOptionsCompareArgs


class CommandTopQueryOptions:
    compare = CommandTopQueryOptionsCompare


class CommandTopQuery:
    description: LangItem = LangItem('command', 'top.query.description')
    args = CommandTopQueryArgs
    options = CommandTopQueryOptions
    shortcut: LangItem = LangItem('command', 'top.query.shortcut')


class CommandTop:
    description: LangItem = LangItem('command', 'top.description')
    bind = CommandTopBind
    unbind = CommandTopUnbind
    config = CommandTopConfig
    query = CommandTopQuery


class CommandTosBindArgsAccount:
    notice: LangItem = LangItem('command', 'tos.bind.args.account.notice')


class CommandTosBindArgs:
    account = CommandTosBindArgsAccount


class CommandTosBind:
    description: LangItem = LangItem('command', 'tos.bind.description')
    args = CommandTosBindArgs
    shortcut: LangItem = LangItem('command', 'tos.bind.shortcut')


class CommandTosUnbind:
    description: LangItem = LangItem('command', 'tos.unbind.description')
    shortcut: LangItem = LangItem('command', 'tos.unbind.shortcut')


class CommandTosConfigOptionsDefaultCompareArgsCompare:
    notice: LangItem = LangItem('command', 'tos.config.options.default_compare.args.compare.notice')


class CommandTosConfigOptionsDefaultCompareArgs:
    compare = CommandTosConfigOptionsDefaultCompareArgsCompare


class CommandTosConfigOptionsDefaultCompare:
    help: LangItem = LangItem('command', 'tos.config.options.default_compare.help')
    args = CommandTosConfigOptionsDefaultCompareArgs


class CommandTosConfigOptions:
    default_compare = CommandTosConfigOptionsDefaultCompare


class CommandTosConfig:
    description: LangItem = LangItem('command', 'tos.config.description')
    options = CommandTosConfigOptions
    shortcut: LangItem = LangItem('command', 'tos.config.shortcut')


class CommandTosQueryArgsWho:
    notice: LangItem = LangItem('command', 'tos.query.args.who.notice')


class CommandTosQueryArgs:
    who = CommandTosQueryArgsWho


class CommandTosQueryOptionsCompareArgsCompare:
    notice: LangItem = LangItem('command', 'tos.query.options.compare.args.compare.notice')


class CommandTosQueryOptionsCompareArgs:
    compare = CommandTosQueryOptionsCompareArgsCompare


class CommandTosQueryOptionsCompare:
    help: LangItem = LangItem('command', 'tos.query.options.compare.help')
    args = CommandTosQueryOptionsCompareArgs


class CommandTosQueryOptions:
    compare = CommandTosQueryOptionsCompare


class CommandTosQuery:
    description: LangItem = LangItem('command', 'tos.query.description')
    args = CommandTosQueryArgs
    options = CommandTosQueryOptions
    shortcut: LangItem = LangItem('command', 'tos.query.shortcut')


class CommandTos:
    description: LangItem = LangItem('command', 'tos.description')
    bind = CommandTosBind
    unbind = CommandTosUnbind
    config = CommandTosConfig
    query = CommandTosQuery


class Command:
    root = CommandRoot
    tetrio = CommandTetrio
    top = CommandTop
    tos = CommandTos


class Lang(LangModel):
    interaction = Interaction
    error = Error
    template = Template
    bind = Bind
    record = Record
    stats = Stats
    template_ui = TemplateUi
    help = Help
    prompt = Prompt
    retry = Retry
    command = Command
