"""add tetrio display mask

迁移 ID: 74640f698d8b
父迁移: b27a3a31cb38
创建时间: 2026-09-27 05:41:06.137369

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = '74640f698d8b'
down_revision: str | Sequence[str] | None = 'b27a3a31cb38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = '') -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nb_t_io_mask',
        sa.Column('uid', sa.String(length=24), nullable=False),
        sa.Column('field', sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint('uid', 'field', name=op.f('pk_nb_t_io_mask')),
        info={'bind_key': 'nonebot_plugin_tetris_stats'},
    )
    # ### end Alembic commands ###


def downgrade(name: str = '') -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nb_t_io_mask')
    # ### end Alembic commands ###
