"""add query_params to historical data

迁移 ID: b27a3a31cb38
父迁移: 3a294ff14610
创建时间: 2026-03-24 20:23:34.098235

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = 'b27a3a31cb38'
down_revision: str | Sequence[str] | None = '3a294ff14610'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = '') -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nb_t_io_hist_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_params', sa.JSON(), nullable=True))

    with op.batch_alter_table('nb_t_tos_hist_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_params', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = '') -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nb_t_tos_hist_data', schema=None) as batch_op:
        batch_op.drop_column('query_params')

    with op.batch_alter_table('nb_t_io_hist_data', schema=None) as batch_op:
        batch_op.drop_column('query_params')

    # ### end Alembic commands ###
